swagger: "2.0"
info:
  description: Backend server documentation
  version: "1.0.0"
  title: "Backend"
host: "149.156.146.249:60001"
basePath: "/api"
tags:
  - name: "user"
    description: "User management"
schemes:
  - "http"
paths:
  /status:
    get:
      summary: "Get API status"
      description: ""
      operationId: "getStatus"
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: '#/definitions/ApiStatus'
  /login:
    post:
      tags:
        - "user"
      summary: "Login as user"
      description: ""
      operationId: "loginUser"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/LoginUser"
      responses:
        200:
          description: "OK"
          schema:
            $ref: '#/definitions/BearerToken'
        400:
          description: "Bad request"
  /user:
    post:
      tags:
        - "user"
      summary: "Create new user"
      description: ""
      operationId: "createUser"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/NewUser"
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: '#/definitions/User'
        400:
          description: "Bad request"
definitions:
  BearerToken:
    type: "object"
    properties:
      token:
        type: "string"
  LoginUser:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
  NewUser:
    type: "object"
    properties:
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
  User:
    type: "object"
    properties:
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      disabled:
        type: "boolean"
  ApiStatus:
    type: "object"
    properties:
      status:
        type: "string"
