openapi: 3.0.0
info:
  description: Backend server documentation
  version: 1.0.0
  title: Backend
tags:
  - name: user
    description: User management
  - name: status
    description: API status and managment
  - name: ticket
    description: Support Ticket managment
  - name: trip
    description: Trip authoring and managment
paths:
  /status:
    get:
      tags:
        - status
      summary: Get API status
      description: Get current API status
      operationId: getStatus
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiStatus"
  /login:
    post:
      tags:
        - user
      summary: Login as user
      description: Get JWT token by providing user email and password
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUser"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BearerToken"
        "400":
          description: Bad request
  /user:
    post:
      tags:
        - user
      summary: Create new user
      description: Create new user with specified details.
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewUser"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Bad request
    get:
      security:
        - bearerAuth: []
      tags:
        - user
      summary: Get current user
      description: Get details of currently logged in user
      operationId: getCurrentUser
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Bad request
  "/user/{email}":
    patch:
      security:
        - bearerAuth: []
      tags:
        - user
      summary: Patch user
      description: "At least one field is required. Only admin can specify roles and disabled fields.
Non-admin user can only patch themselves. Admin can patch anyone."
      operationId: patchUser
      parameters:
        - name: email
          in: path
          description: User email
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: OK
        "400":
          description: Bad request
  /users:
    get:
      security:
        - bearerAuth: []
      tags:
        - user
      summary: Get all users
      description: Get list of every user. This can be only done by the administrator.
      operationId: getUsers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
        "400":
          description: Bad request
  /ticket:
    get:
      security:
        - bearerAuth: []
      tags:
        - ticket
      summary: Get current user tickets
      description: Only admin can use all=true. If true return every ticket regardless of current user.
      parameters:
        - name: all
          in: query
          required: false
          description: "Return all tickets if all is true and current user role is admin"
          schema:
            type: boolean
      operationId: getTickets
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tickets"
        "400":
          description: Bad request
    post:
      security:
        - bearerAuth: []
      tags:
        - ticket
      summary: Create new ticket
      description: "Create new ticket which author is logged user"
      operationId: createTicket
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTicket'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        "400":
          description: Bad request
  /ticket/{ticketId}:
    get:
      security:
        - bearerAuth: []
      tags:
        - ticket
      summary: Get ticket
      description: "User can only get their own tickets"
      operationId: getTicket
      parameters:
        - name: ticketId
          in: path
          description: ticket id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketWithComments'
        "400":
          description: "Bad request"
    patch:
      security:
        - bearerAuth: []
      tags:
        - ticket
      summary: Patch ticket
      description: "At least one field is required. Non-admin user can only patch themselves.
       Admin can patch anyone."
      operationId: patchTicket
      parameters:
        - name: ticketId
          in: path
          description: ticket id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchTicket'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatchTicket'
        "400":
          description: Bad request
  /ticket/{ticketId}/comment:
    post:
      security:
        - bearerAuth: []
      tags:
        - ticket
      summary: Create new comment
      description: "Users can only add comments to their own tickets"
      parameters:
        - name: ticketId
          in: path
          description: ticket id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewComment'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentWithAuthor'
        "400":
          description: Bad request
  /trips:
    get:
      security:
        - bearerAuth: []
      tags:
        - trip
      summary: Get current user added trips
      description: Shows all trips created by current guide user.
      operationId: getTrips
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trips'
        "400":
          description: Bad request
  /trip/{tripId}:
    get:
      security:
        - bearerAuth: []
      tags:
        - trip
      summary: Get current user trip
      description: Shows only one trip with provided tripId created by user.
      operationId: getTrip
      parameters:
        - name: tripId
          in: path
          description: trip id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        "400":
          description: Bad request
    patch:
      security:
        - bearerAuth: []
      tags:
        - trip
      summary: Update trip
      description: "patches trip that was created by user provided by user(guide)"
      operationId: update
      parameters:
        - name: tripId
          in: path
          description: trip id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trip'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trip"
        "400":
          description: Bad request
  /trip:
    post:
      security:
        - bearerAuth: []
      tags:
        - trip
      summary: Create new trip
      description: "Create new trip with informations provided by the user (must be a guide)"
      operationId: createTrip
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trip'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trip"
        "400":
          description: Bad request
  /trip/{tripId}/comments:
    get:
      security:
        - bearerAuth: []
      tags:
        - trip
      summary: Get all comments for specific trip
      description: "Get all comments for trip with given id"
      operationId: getTripComments
      parameters:
        - name: tripId
          in: path
          description: trip id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comments'
        "400":
          description: Bad request
  /trip/{tripId}/comment:
    post:
      security:
        - bearerAuth: []
      tags:
        - trip
      summary: Create new trip comment
      description: "Create new comment for specific trip"
      operationId: createTripComment
      parameters:
        - name: tripId
          in: path
          description: trip id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewComment'
        required: true
      responses:
        "200":
          description: OK
        "400":
          description: Bad request
  /trip/{tripId}/comment/{commentId}:
    patch:
      security:
        - bearerAuth: []
      tags:
        - trip
      summary: Update trip comment
      description: "Update comment for specific trip"
      operationId: patchTripComment
      parameters:
        - name: tripId
          in: path
          description: trip id
          required: true
          schema:
            type: integer
        - name: commentId
          in: path
          description: comment id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchComment'
        required: true
      responses:
        "200":
          description: OK
        "400":
          description: Bad request
servers:
  - url: http://149.156.146.249:60001/api
    description: Production server
  - url: http://149.156.146.249:60001/api-pre
    description: Staging server
  - url: http://127.0.0.1:8090
    description: Local server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    BearerToken:
      type: object
      properties:
        token:
          type: string
    LoginUser:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    NewUser:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"
    User:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        disabled:
          type: boolean
        roles:
          type: array
          items:
            type: string
    Tickets:
      type: array
      items:
        $ref: "#/components/schemas/Ticket"
    Ticket:
      type: object
      properties:
        id:
          type: integer
        closed:
          type: boolean
        author:
          type: string
        createDate:
          type: string
        content:
          type: string
    NewTicket:
      type: object
      properties:
        content:
          type: string
      required:
        - content
    PatchTicket:
      type: object
      properties:
        content:
          type: string
        closed:
          type: boolean
      required:
        - content
        - closed
    Comments:
      type: array
      items:
        $ref: '#/components/schemas/Comment'
    Comment:
      type: object
      properties:
        content:
          type: string
        author:
          type: string
    CommentsWithAuthors:
      type: array
      items:
        $ref: '#/components/schemas/CommentWithAuthor'
    CommentWithAuthor:
      type: object
      properties:
        content:
          type: string
        author:
          $ref: '#/components/schemas/User'
    NewComment:
      type: object
      properties:
        content:
          type: string
      required:
        - content
    TicketWithComments:
      type: object
      properties:
        ticket:
          $ref: '#/components/schemas/Ticket'
        comments:
          $ref: '#/components/schemas/CommentsWithAuthors'
    ApiStatus:
      type: object
      properties:
        status:
          type: string
    PatchComment:
      type: object
      properties:
        content:
          type: string
        deleted:
          type: boolean
    TripPoint:
      type: object
      properties:
        order:
          type: integer
        coordinates:
          type: string
    TripRoute:
      type: object
      properties:
        name:
          type: string
        points:
          type: array
          items:
            $ref: '#/components/schemas/TripPoint'
    Trip:
      type: object
      properties:
        id:
          type: integer
        cost:
          type: integer
        description:
          type: string
        peopleLimit:
          type: integer
        dateTrip:
          type: string
        active:
          type: boolean
        guide:
          $ref: '#/components/schemas/User'
        route:
          $ref: '#/components/schemas/TripRoute'
    Trips:
      type: array
      items:
        $ref: '#/components/schemas/Trip'
    TripComment:
      type: object
      properties:
        author:
          type: string
        comment:
          type: string
    TripComments:
      type: array
      items:
        $ref: '#/components/schemas/TripComment'
    PatchTripComment:
      type: object
      properties:
        content:
          type: string
        deleted:
          type: boolean
